services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"   #Host : 5433 , Container : 5432

  myapp:
    build: ./myapp
    image: myapp #explicilty define image name
    container_name: myapp-container
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"

  mylearning:
    build: ./mylearning
    image: mylearning #explicilty define image name
    container_name: mylearning-container
