services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  myapp:
    image: ${IMAGE_MYAPP_STAGING} #will be provided by your deploy-staging job via environment variables from ci-cd.yml
    container_name: myapp-staging
    working_dir: /app/myapp
    volumes:
      - .:/app    # bind mount repo root into /app
    depends_on:
      - db
    environment: #Python uses DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD, APP_ENV. Here, DB_* are injected by the staging job from environment secrets.
      APP_ENV: staging
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"

  mylearning:
    image: ${IMAGE_MYLEARNING_STAGING} ##will be provided by your deploy-staging job via environment variables from ci-cd.yml
    container_name: mylearning-staging
    working_dir: /app/mylearning
    volumes:
      - .:/app    # same repo root
    environment:
      APP_ENV: staging
