# CI‑only docker-compose.yml (with build: and dev deps) for CI/test and
# It does not participate in deploy stacks.
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"   #Host : 5433 , Container : 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  myapp:
    build:
      context: ./myapp
      args:
        INSTALL_DEV: "true" #build with dev dependencies from *.toml file
    image: myapp #explicilty define docker image name otherwise docker assigns random names.
    container_name: myapp-container
    working_dir: /app
    volumes:
      - ./myapp:/app    # bind mount repo root into /app
    depends_on:
      - db
    environment:
     APP_ENV: ci
     DB_HOST: db
     DB_PORT: 5432
     DB_NAME: mydb
     DB_USER: myuser
     DB_PASSWORD: mypassword
    ports:
      - "8000:8000"

  mylearning:
    build:
      context: ./mylearning
      args:
        INSTALL_DEV: "true" #build with dev dependencies.
    image: mylearning #explicilty define image name
    container_name: mylearning-container
    working_dir: /app
    volumes:
      - ./mylearning:/app   # carefully pick mount project root into /app
    environment:
      APP_ENV: ci
