[mypy]
python_version = 3.11
warn_unused_configs = True
strict = true

[mypy-myapp.*]
ignore_missing_imports = True

[mypy-exercises.*]
ignore_missing_imports = True

[mypy-myapp.core.config]
ignore_errors = True