[mypy]
python_version = 3.11
warn_unused_configs = true
disallow_untyped_decorators = false# We disabling this temporarily. ToDo Set it to true and fix the issue.
strict = true

[mypy-myapp.*]
ignore_missing_imports = true

[mypy-exercises.*]
ignore_missing_imports = true

[mypy-myapp.core.config]
ignore_errors = true

[mypy-pythonjsonlogger.*]
ignore_missing_imports = True
