apiVersion: v1
kind: Secret
metadata:
  name: cluster-monitoring-infra-dev-grafana
  namespace: monitoring
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin          # or your real password