# Note:
# this manifest as documentation, we have kept one file per env, 
# but we still don’t apply them directly; Make overwrites them.
# do not have to keep this file if you create the Secret entirely 
# from the Makefile, but it is nice as documentation.
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials-staging
  namespace: logging
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""