# Install/upgrade both charts with a values-local.yaml.
# Used by Makefile for local check with Minikube
replicaCount: 1 # means the app should run as one pod by default.

# Note: 
# you can avoid hard‑coding the repo path in your Helm 
# values by using tpl + Values so CI can inject the full image 
# name (or repo + tag)
image: # control which container image Kubernetes should run and how it should pull it.
  # If fullName is set, it overrides repository:tag
  fullName: ""      # e.g. ghcr.io/owner/repo/myapp:dev
  repository: ""    # optional fallback for local dev
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP #  means the app is exposed only inside the cluster, not directly outside it.
  port: 8000 # is the port the service listens on and forwards to the app.

resources: # sets CPU and memory requests/limits so Kubernetes knows how much capacity the app needs and what maximum it may use
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Non-secret config; becomes a ConfigMap
# contains non-sensitive environment variables, 
# which are typically turned into a ConfigMap.
config:
  APP_ENV: "dev"
  LOG_LEVEL: "info"
  OTEL_ENABLED: "true"
  OTEL_SERVICE_NAME: "myapp-ci"
  OTEL_EXPORTER_OTLP_ENDPOINT: "api.uptrace.dev:4317"
  DISABLE_CUSTOM_MIDDLEWARE: "false"
  OTEL_TRACES_SAMPLER : "always_on"

# Secret keys; values are provided via external Secret in cluster
# defines the names of secret-backed environment variables that 
# should come from a Kubernetes Secret, not from plain text in the chart
secret:
  name: myapp-secret
  managedByHelm: true        # <--- key flag means “do render a Secret by Helm”
  DB_HOST: mydb-postgres # Postgres chart creates a Service named mydb-postgres on port 5432
  DB_PORT: "5432"
  DB_NAME: mydb
  DB_USER: myuser
  DB_PASSWORD: mypassword
  UPTRACE_TOKEN: "WLfJDCI9dKwaoXgI-Z-jFg"            # override per env / via CI or kubectl
  UPTRACE_DSN: "https://WLfJDCI9dKwaoXgI-Z-jFg@api.uptrace.dev?grpc=4317"

# Optional extra env vars (non-secret) for experiments
# is a place to add optional environment variables later, usually for testing or experiments.
extraEnv: []

# add pod Non-root security Context
# These enforce non-root and limited capabilities at runtime, matching hardened container guidelines.
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001      # must match UID in your myapp Dockerfile
  runAsGroup: 10001
  fsGroup: 10001

# add container Non-root security Context
# These enforce non-root and limited capabilities at runtime, matching hardened container guidelines.
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL