apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-infra-d-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://cluster-monitoring-infra-d-prometheus.monitoring:9090/
        access: proxy
        isDefault: true
        jsonData:
          httpMethod: POST
          timeInterval: 30s
      - name: Alertmanager
        type: alertmanager
        uid: alertmanager
        url: http://cluster-monitoring-infra-d-alertmanager.monitoring:9093/
        access: proxy
        jsonData:
          handleGrafanaManagedAlerts: false
          implementation: prometheus
      - name: Loki
        type: loki
        uid: loki
        url: http://myapp-logging-dev-loki.logging.svc:3100
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000
          timeout: 60
