{{- if eq .Values.global.environment "dev" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-dev
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "5Gi" .Values.grafana.storage.size }}
  storageClassName: {{ default "standard" .Values.grafana.storageClassName }}
{{- end }}