apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://cluster-monitoring-infra-d-prometheus.monitoring:9090
    isDefault: true
    jsonData:
      timeInterval: "30s"

  - name: Loki
    type: loki
    access: proxy
    url: http://myapp-logging-dev-loki.logging:3100
    isDefault: false