# This prevents any future changes (extra exporters, more dashboards, etc.) from overwhelming the cluster.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota-dev
  namespace: monitoring
spec:
  # hard:
  #   requests.cpu: "4"       # total requested CPU in this namespace
  #   limits.cpu: "6"
  #   requests.memory: 6Gi    # total requested memory
  #   limits.memory: 10Gi
  #   pods: "50"