---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-monitoring-infra-environments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - environment: dev
            namespace: monitoring
            targetRevision: main
            valuesFile: "kube-prometheus-stack-values-dev.yaml"
          # - environment: staging
          #   namespace: monitoring
          #   targetRevision: main
          #   valuesFile: "kube-prometheus-stack-values-staging.yaml"
          # - environment: prod
          #   namespace: monitoring
          #   targetRevision: main
          #   valuesFile: "kube-prometheus-stack-values-prod.yaml"
  template:
    metadata:
      name: cluster-monitoring-infra-{{.environment}}
      labels:
        app.kubernetes.io/part-of: myapp
        app.kubernetes.io/component: cluster-monitoring
        app.kubernetes.io/environment: "{{.environment}}"
    spec:
      project: default
      sources:
        # 1) Main Helm chart source: kube-prometheus-stack from prometheus-community
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 67.1.0   # or latest tested version

          helm:
            valueFiles:
              - $values/infra/k8s/monitoring/{{.valuesFile}}

        # 2) Values-from-Git source so $values/... works
        - repoURL: https://github.com/gMpHSpLB/pythonworkspace.git
          targetRevision: "{{.targetRevision}}"
          ref: values
      destination:
        # If each Argo CD instance runs in its own cluster:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    {{- if eq .environment "prod" }}
    spec:
      syncPolicy:
        automated: null
    {{- else if eq .environment "dev" }}
    spec:
      syncPolicy:
        automated: null        
    {{- else }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    {{- end }}
