name: Monorepo CI

on:
  push:
    branches: [ main ]

jobs:
  myapp:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Poetry
      run: |
        cd myapp
        pip install poetry

    - name: Install dependencies
      run: |
        cd myapp
        poetry install --no-root

    - name: Wait for DB
      run: |
        cd myapp
        sleep 5

    - name: Run tests
      env:
        DB_HOST: localhost
      run: |
        cd myapp
        poetry run pytest

  mylearning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      run: |
        cd mylearning
        pip install poetry

    - name: Install dependencies
      run: |
        cd mylearning
        poetry install --no-root

    - name: Run script
      run: |
        cd mylearning
        poetry run python exercises/testexcercise.py

  docker:
    runs-on: ubuntu-latest
    needs: [myapp, mylearning]  # run only if tests pass

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t myapp ./myapp

    - name: Build Docker image
      run: docker build -t mylearning ./mylearning

    - name: Run container myapp
      run: |
        docker run -d -p 8000:8000 --name myapp-test myapp
        sleep 5
        curl -f http://localhost:8000 || exit 1

    - name: Run container mylearning
      run: docker run --name mylearning-test mylearning

    - name: Stop container
      run: docker stop myapp-test

    - name: Stop container
      run: docker stop mylearning-test
