name: Monorepo CI

on:
  push:
    branches: [ main ]

jobs:
  # ---------- CI - Need to run docker only ----------
  docker:
    runs-on: ubuntu-latest
    #needs: [myapp, mylearning]

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker images
      run: docker compose build

    - name: Run Docker tests
      run: make test-docker

    - name: Check API
      run: |
        make run
        make check-api